### ISSUE TITLE
mixed-up allocation of parameters

### ISSUE THREAD

**Issue by smcatala** [jo/docuri#11]
```javascript
docuri.route('(/*endpoint/)_view/:view(/*key)','view');
docuri.view("/endpoint/_view/view"); // {endpoint: ["view"], view: "endpoint"}  => mixed-up!
```
this behaviour can be explained as follows:
`routeToRegExp(String)` first parses named parameters (line 30) then parses splat parameters (line 35), so that the `:view` named parameter is pushed first into the `keys` array, before the `*endpoint` splat parameter. 
On line 69 of `extractParameters(Object, String)`, the wrong parameter is fetched because the index of the parameter extracted by RegExp.exec(String) does not match the index of the `route.keys` parameter: the `*endpoint` parameter is extracted first, before the `:view` parameter.

a possible simple fix would be to sort the `keys` object in `routeToRegExp(String)` in the order in which they appear in the route source, for example as follows:
```javascript
function routeToRegExp(src) {
  var keys = [];

  var route = src.replace(escapeRegExp, '\\$&')
    .replace(optionalParam, '(?:$1)?')
    .replace(namedParam, function(match, optional) {
      keys.push({'name': match, 'offset': arguments[arguments.length-2]}); // add the offset of the match

      return optional ? match : '([^/?]+)';
    })
    .replace(splatParam, function(match) {
      keys.push({'name': match, 'offset': arguments[arguments.length-2]}); // add the offset of the match

      return '([^?]*?)';
    });

  keys = keys.sort(function(a, b) { // first sort the keys by match offset
      if (a.offset < b.offset) return -1;
      if (a.offset < b.offset) return -1;
      return 0;
    })
    .reduce(function(memo, key) {
      var value = '\\' + key.name; // ignore the offset component

      memo[key.name] = new RegExp(value + '(\\/|\\)|\\(|$)'); // ignore the offset component

      return memo;
    }, {});

  return {
    src: src,
    exp: new RegExp('^' + route + '(?:\\?([\\s\\S]*))?$'),
    keys: keys
  }
}
```
Note that accessing object properties by their index is generally not recommended (line 68 of `extractParameters(Object, String)`: the index argument `i` of the reduce function), so a cleaner fix would require a more involved fix, such as changing the `route.keys` property to an Array, each entry of which is the corresponding entry of the current `route.keys` object. Array entries can be sorted as above, so that line 68 of `extractParameters(Object, String)` is guarantied to supply the proper parameter.

**Comment by jo** [comment]
Good catch!

Thank you for this profound description.
