### ISSUE TITLE
Use template strings instead of :id and *path

### ISSUE THREAD

**Issue by jo** [jo/docuri#19]
Use [template strings](https://github.com/lukehoban/es6features#template-strings) instead of `:id` and `**path`, like proposed in this [template url RFC](http://tools.ietf.org/html/draft-gregorio-uritemplate-05).

**Comment by denis-sokolov** [comment]
Perhaps I misunderstand, so correct me if I'm wrong.
But I am under an impression that template strings is just a fancy way to do concatenation and string processing, but it assumes that you have the template and the values at the same time.
In `docuri`, however, we want to first pass the template string, and only later pass the values in.
If my understand is correct, template strings hardly help `docuri` at all.

**Comment by jo** [comment]
I think they are a nice way to express a docuri. I want to switch back from using `:param` because I want to be able to use the colon as seperator, instead of `/`.

But I agree with your arguments stated in https://github.com/jo/docuri/issues/13#issuecomment-108421489 and closing this.

Thanks!
