### ISSUE TITLE
Cannot call route since 4.2.0

### ISSUE THREAD

**Issue by mciparelli** [jo/docuri#26]
```js
var path = 'document/:docKey';
docuri.route(path, path);
docuri[path]; // function in <= v4.1.1, undefined in v4.2.0
```

**Comment by mciparelli** [comment]
Noticed when my tests started to fail as I was trying to call `docuri[path]`

**Comment by mciparelli** [comment]
Apparently this commit introduced a backwards incompatible change and now docs changed. You should've released a major version :(

**Comment by jo** [comment]
Yes, that was wrong.

I just added a note on the breaking release: https://github.com/jo/docuri/releases/tag/v4.1.1

Sorry about that!
